language: ruby

cache: bundler

rvm:
- 2.0.0

addons:
  postgresql: 9.3

before_script:
- ./scripts/travis

env:
  matrix:
  - DATABASE_URL="postgres://localhost/evercam_tst"
  global:
  - secure: BTrnsgd5wuCTmOOCsFDZ4+JFUj6bvTmwkYvW3snzLBmA1g58mqA/HdqL50tKdRaCb2/Hw0VfNIRvuEmg3zXY4bwF6OpcLKnnwG78MCQqwkHcMaSIkH8xDSjpwkat/UQIHCGuz5U13nGbb6+7UAjQPufJ5S340y0RnrNSl8ZYUSs=
  - secure: lhJxEDoWEEbpg6j69WrOkiQupnOKMyPPK2bLTaEtHsaYBU9c5pAOvBeE7MSd2f5WTz1+ZhE//GMPtlkzGn/xrsxFTQvnhEqv0H1kfpAdoeRyt2ySxZX7H5lThscvVEUfNFmYr7MESYzUNkPQOgVBtIuS6eCtXxyJ15aLEKcSXzE=

branches:
  only: master

deploy:
  provider: heroku
  app:
    master: powerful-ocean-5002
  api_key:
    secure: ZztBXxYMZxZv65UJCKeLQF0amEy+5HX8/izUlFPD90AIosok7C2IhM0VhWtVlSYS4GvAagbvkZe4OR89vGYJaBzM8akA3J1X7PRm2AD+GEKmpxTkCrVUkR5iCoLDG+10wV50yYPKizR9Noi9DBpZcSnPOSHDHuIIvdWBjz63Nfw=
  run:
  - rake db:migrate
  - restart
